sonar.projectKey=kindred-98_StockGuard
sonar.organization=kindred-98
sonar.projectName=StockGuard
sonar.projectVersion=1.0.0
sonar.sources=stockguard
sonar.tests=tests
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
